// Generated by scripts/generate-compliance-schema.mjs from Graph's beta $metadata — do not edit by hand.

export type ComplianceFieldType = "boolean" | "integer" | "string" | { enum: string };
export type CompliancePropertyType = ComplianceFieldType | { object: string; list: boolean };

/** Every compliance policy type Graph defines, and what each of its properties holds. */
export const COMPLIANCE_TYPES: Record<string, Record<string, CompliancePropertyType>> = {
  "androidCompliancePolicy": {
    "advancedThreatProtectionRequiredSecurityLevel": {
      "enum": "deviceThreatProtectionLevel"
    },
    "conditionStatementId": "string",
    "deviceThreatProtectionEnabled": "boolean",
    "deviceThreatProtectionRequiredSecurityLevel": {
      "enum": "deviceThreatProtectionLevel"
    },
    "minAndroidSecurityPatchLevel": "string",
    "osMaximumVersion": "string",
    "osMinimumVersion": "string",
    "passwordExpirationDays": "integer",
    "passwordMinimumLength": "integer",
    "passwordMinutesOfInactivityBeforeLock": "integer",
    "passwordPreviousPasswordBlockCount": "integer",
    "passwordRequired": "boolean",
    "passwordRequiredType": {
      "enum": "androidRequiredPasswordType"
    },
    "passwordSignInFailureCountBeforeFactoryReset": "integer",
    "requiredPasswordComplexity": {
      "enum": "androidRequiredPasswordComplexity"
    },
    "restrictedApps": {
      "object": "appListItem",
      "list": true
    },
    "securityBlockDeviceAdministratorManagedDevices": "boolean",
    "securityBlockJailbrokenDevices": "boolean",
    "securityDisableUsbDebugging": "boolean",
    "securityPreventInstallAppsFromUnknownSources": "boolean",
    "securityRequireCompanyPortalAppIntegrity": "boolean",
    "securityRequireGooglePlayServices": "boolean",
    "securityRequireSafetyNetAttestationBasicIntegrity": "boolean",
    "securityRequireSafetyNetAttestationCertifiedDevice": "boolean",
    "securityRequireUpToDateSecurityProviders": "boolean",
    "securityRequireVerifyApps": "boolean",
    "storageRequireEncryption": "boolean"
  },
  "androidDeviceOwnerCompliancePolicy": {
    "advancedThreatProtectionRequiredSecurityLevel": {
      "enum": "deviceThreatProtectionLevel"
    },
    "deviceThreatProtectionEnabled": "boolean",
    "deviceThreatProtectionRequiredSecurityLevel": {
      "enum": "deviceThreatProtectionLevel"
    },
    "minAndroidSecurityPatchLevel": "string",
    "osMaximumVersion": "string",
    "osMinimumVersion": "string",
    "passwordExpirationDays": "integer",
    "passwordMinimumLength": "integer",
    "passwordMinimumLetterCharacters": "integer",
    "passwordMinimumLowerCaseCharacters": "integer",
    "passwordMinimumNonLetterCharacters": "integer",
    "passwordMinimumNumericCharacters": "integer",
    "passwordMinimumSymbolCharacters": "integer",
    "passwordMinimumUpperCaseCharacters": "integer",
    "passwordMinutesOfInactivityBeforeLock": "integer",
    "passwordPreviousPasswordCountToBlock": "integer",
    "passwordRequired": "boolean",
    "passwordRequiredType": {
      "enum": "androidDeviceOwnerRequiredPasswordType"
    },
    "requireNoPendingSystemUpdates": "boolean",
    "securityBlockJailbrokenDevices": "boolean",
    "securityRequiredAndroidSafetyNetEvaluationType": {
      "enum": "androidSafetyNetEvaluationType"
    },
    "securityRequireIntuneAppIntegrity": "boolean",
    "securityRequireSafetyNetAttestationBasicIntegrity": "boolean",
    "securityRequireSafetyNetAttestationCertifiedDevice": "boolean",
    "storageRequireEncryption": "boolean"
  },
  "androidForWorkCompliancePolicy": {
    "deviceThreatProtectionEnabled": "boolean",
    "deviceThreatProtectionRequiredSecurityLevel": {
      "enum": "deviceThreatProtectionLevel"
    },
    "minAndroidSecurityPatchLevel": "string",
    "osMaximumVersion": "string",
    "osMinimumVersion": "string",
    "passwordExpirationDays": "integer",
    "passwordMinimumLength": "integer",
    "passwordMinutesOfInactivityBeforeLock": "integer",
    "passwordPreviousPasswordBlockCount": "integer",
    "passwordRequired": "boolean",
    "passwordRequiredType": {
      "enum": "androidRequiredPasswordType"
    },
    "passwordSignInFailureCountBeforeFactoryReset": "integer",
    "requiredPasswordComplexity": {
      "enum": "androidRequiredPasswordComplexity"
    },
    "securityBlockJailbrokenDevices": "boolean",
    "securityDisableUsbDebugging": "boolean",
    "securityPreventInstallAppsFromUnknownSources": "boolean",
    "securityRequireCompanyPortalAppIntegrity": "boolean",
    "securityRequiredAndroidSafetyNetEvaluationType": {
      "enum": "androidSafetyNetEvaluationType"
    },
    "securityRequireGooglePlayServices": "boolean",
    "securityRequireSafetyNetAttestationBasicIntegrity": "boolean",
    "securityRequireSafetyNetAttestationCertifiedDevice": "boolean",
    "securityRequireUpToDateSecurityProviders": "boolean",
    "securityRequireVerifyApps": "boolean",
    "storageRequireEncryption": "boolean",
    "workProfileInactiveBeforeScreenLockInMinutes": "integer",
    "workProfilePasswordExpirationInDays": "integer",
    "workProfilePasswordMinimumLength": "integer",
    "workProfilePasswordRequiredType": {
      "enum": "androidForWorkRequiredPasswordType"
    },
    "workProfilePreviousPasswordBlockCount": "integer",
    "workProfileRequiredPasswordComplexity": {
      "enum": "androidRequiredPasswordComplexity"
    },
    "workProfileRequirePassword": "boolean"
  },
  "androidWorkProfileCompliancePolicy": {
    "advancedThreatProtectionRequiredSecurityLevel": {
      "enum": "deviceThreatProtectionLevel"
    },
    "deviceThreatProtectionEnabled": "boolean",
    "deviceThreatProtectionRequiredSecurityLevel": {
      "enum": "deviceThreatProtectionLevel"
    },
    "minAndroidSecurityPatchLevel": "string",
    "osMaximumVersion": "string",
    "osMinimumVersion": "string",
    "passwordExpirationDays": "integer",
    "passwordMinimumLength": "integer",
    "passwordMinutesOfInactivityBeforeLock": "integer",
    "passwordPreviousPasswordBlockCount": "integer",
    "passwordRequired": "boolean",
    "passwordRequiredType": {
      "enum": "androidRequiredPasswordType"
    },
    "passwordSignInFailureCountBeforeFactoryReset": "integer",
    "requiredPasswordComplexity": {
      "enum": "androidRequiredPasswordComplexity"
    },
    "securityBlockJailbrokenDevices": "boolean",
    "securityDisableUsbDebugging": "boolean",
    "securityPreventInstallAppsFromUnknownSources": "boolean",
    "securityRequireCompanyPortalAppIntegrity": "boolean",
    "securityRequiredAndroidSafetyNetEvaluationType": {
      "enum": "androidSafetyNetEvaluationType"
    },
    "securityRequireGooglePlayServices": "boolean",
    "securityRequireSafetyNetAttestationBasicIntegrity": "boolean",
    "securityRequireSafetyNetAttestationCertifiedDevice": "boolean",
    "securityRequireUpToDateSecurityProviders": "boolean",
    "securityRequireVerifyApps": "boolean",
    "storageRequireEncryption": "boolean",
    "workProfileInactiveBeforeScreenLockInMinutes": "integer",
    "workProfilePasswordExpirationInDays": "integer",
    "workProfilePasswordMinimumLength": "integer",
    "workProfilePasswordRequiredType": {
      "enum": "androidWorkProfileRequiredPasswordType"
    },
    "workProfilePreviousPasswordBlockCount": "integer",
    "workProfileRequiredPasswordComplexity": {
      "enum": "androidRequiredPasswordComplexity"
    },
    "workProfileRequirePassword": "boolean"
  },
  "aospDeviceOwnerCompliancePolicy": {
    "minAndroidSecurityPatchLevel": "string",
    "osMaximumVersion": "string",
    "osMinimumVersion": "string",
    "passwordMinimumLength": "integer",
    "passwordMinutesOfInactivityBeforeLock": "integer",
    "passwordRequired": "boolean",
    "passwordRequiredType": {
      "enum": "androidDeviceOwnerRequiredPasswordType"
    },
    "securityBlockJailbrokenDevices": "boolean",
    "storageRequireEncryption": "boolean"
  },
  "iosCompliancePolicy": {
    "advancedThreatProtectionRequiredSecurityLevel": {
      "enum": "deviceThreatProtectionLevel"
    },
    "deviceThreatProtectionEnabled": "boolean",
    "deviceThreatProtectionRequiredSecurityLevel": {
      "enum": "deviceThreatProtectionLevel"
    },
    "managedEmailProfileRequired": "boolean",
    "osMaximumBuildVersion": "string",
    "osMaximumVersion": "string",
    "osMinimumBuildVersion": "string",
    "osMinimumVersion": "string",
    "passcodeBlockSimple": "boolean",
    "passcodeExpirationDays": "integer",
    "passcodeMinimumCharacterSetCount": "integer",
    "passcodeMinimumLength": "integer",
    "passcodeMinutesOfInactivityBeforeLock": "integer",
    "passcodeMinutesOfInactivityBeforeScreenTimeout": "integer",
    "passcodePreviousPasscodeBlockCount": "integer",
    "passcodeRequired": "boolean",
    "passcodeRequiredType": {
      "enum": "requiredPasswordType"
    },
    "restrictedApps": {
      "object": "appListItem",
      "list": true
    },
    "securityBlockJailbrokenDevices": "boolean"
  },
  "macOSCompliancePolicy": {
    "advancedThreatProtectionRequiredSecurityLevel": {
      "enum": "deviceThreatProtectionLevel"
    },
    "deviceCompliancePolicyScript": {
      "object": "deviceCompliancePolicyScript",
      "list": false
    },
    "deviceThreatProtectionEnabled": "boolean",
    "deviceThreatProtectionRequiredSecurityLevel": {
      "enum": "deviceThreatProtectionLevel"
    },
    "firewallBlockAllIncoming": "boolean",
    "firewallEnabled": "boolean",
    "firewallEnableStealthMode": "boolean",
    "gatekeeperAllowedAppSource": {
      "enum": "macOSGatekeeperAppSources"
    },
    "osMaximumBuildVersion": "string",
    "osMaximumVersion": "string",
    "osMinimumBuildVersion": "string",
    "osMinimumVersion": "string",
    "passwordBlockSimple": "boolean",
    "passwordExpirationDays": "integer",
    "passwordMinimumCharacterSetCount": "integer",
    "passwordMinimumLength": "integer",
    "passwordMinutesOfInactivityBeforeLock": "integer",
    "passwordPreviousPasswordBlockCount": "integer",
    "passwordRequired": "boolean",
    "passwordRequiredType": {
      "enum": "requiredPasswordType"
    },
    "storageRequireEncryption": "boolean",
    "systemIntegrityProtectionEnabled": "boolean"
  },
  "windows10CompliancePolicy": {
    "activeFirewallRequired": "boolean",
    "antiSpywareRequired": "boolean",
    "antivirusRequired": "boolean",
    "bitLockerEnabled": "boolean",
    "codeIntegrityEnabled": "boolean",
    "configurationManagerComplianceRequired": "boolean",
    "defenderEnabled": "boolean",
    "defenderVersion": "string",
    "deviceCompliancePolicyScript": {
      "object": "deviceCompliancePolicyScript",
      "list": false
    },
    "deviceThreatProtectionEnabled": "boolean",
    "deviceThreatProtectionRequiredSecurityLevel": {
      "enum": "deviceThreatProtectionLevel"
    },
    "earlyLaunchAntiMalwareDriverEnabled": "boolean",
    "firmwareProtectionEnabled": "boolean",
    "kernelDmaProtectionEnabled": "boolean",
    "memoryIntegrityEnabled": "boolean",
    "mobileOsMaximumVersion": "string",
    "mobileOsMinimumVersion": "string",
    "osMaximumVersion": "string",
    "osMinimumVersion": "string",
    "passwordBlockSimple": "boolean",
    "passwordExpirationDays": "integer",
    "passwordMinimumCharacterSetCount": "integer",
    "passwordMinimumLength": "integer",
    "passwordMinutesOfInactivityBeforeLock": "integer",
    "passwordPreviousPasswordBlockCount": "integer",
    "passwordRequired": "boolean",
    "passwordRequiredToUnlockFromIdle": "boolean",
    "passwordRequiredType": {
      "enum": "requiredPasswordType"
    },
    "requireHealthyDeviceReport": "boolean",
    "rtpEnabled": "boolean",
    "secureBootEnabled": "boolean",
    "signatureOutOfDate": "boolean",
    "storageRequireEncryption": "boolean",
    "tpmRequired": "boolean",
    "validOperatingSystemBuildRanges": {
      "object": "operatingSystemVersionRange",
      "list": true
    },
    "virtualizationBasedSecurityEnabled": "boolean",
    "wslDistributions": {
      "object": "wslDistributionConfiguration",
      "list": true
    }
  },
  "windows10MobileCompliancePolicy": {
    "activeFirewallRequired": "boolean",
    "bitLockerEnabled": "boolean",
    "codeIntegrityEnabled": "boolean",
    "earlyLaunchAntiMalwareDriverEnabled": "boolean",
    "osMaximumVersion": "string",
    "osMinimumVersion": "string",
    "passwordBlockSimple": "boolean",
    "passwordExpirationDays": "integer",
    "passwordMinimumCharacterSetCount": "integer",
    "passwordMinimumLength": "integer",
    "passwordMinutesOfInactivityBeforeLock": "integer",
    "passwordPreviousPasswordBlockCount": "integer",
    "passwordRequired": "boolean",
    "passwordRequiredType": {
      "enum": "requiredPasswordType"
    },
    "passwordRequireToUnlockFromIdle": "boolean",
    "secureBootEnabled": "boolean",
    "storageRequireEncryption": "boolean",
    "validOperatingSystemBuildRanges": {
      "object": "operatingSystemVersionRange",
      "list": true
    }
  },
  "windows81CompliancePolicy": {
    "osMaximumVersion": "string",
    "osMinimumVersion": "string",
    "passwordBlockSimple": "boolean",
    "passwordExpirationDays": "integer",
    "passwordMinimumCharacterSetCount": "integer",
    "passwordMinimumLength": "integer",
    "passwordMinutesOfInactivityBeforeLock": "integer",
    "passwordPreviousPasswordBlockCount": "integer",
    "passwordRequired": "boolean",
    "passwordRequiredType": {
      "enum": "requiredPasswordType"
    },
    "storageRequireEncryption": "boolean"
  },
  "windowsPhone81CompliancePolicy": {
    "osMaximumVersion": "string",
    "osMinimumVersion": "string",
    "passwordBlockSimple": "boolean",
    "passwordExpirationDays": "integer",
    "passwordMinimumCharacterSetCount": "integer",
    "passwordMinimumLength": "integer",
    "passwordMinutesOfInactivityBeforeLock": "integer",
    "passwordPreviousPasswordBlockCount": "integer",
    "passwordRequired": "boolean",
    "passwordRequiredType": {
      "enum": "requiredPasswordType"
    },
    "storageRequireEncryption": "boolean"
  }
};

/** Members of the enums those properties use, in Graph's order — the first is what an unset property reports. */
export const COMPLIANCE_ENUMS: Record<string, string[]> = {
  "androidDeviceOwnerRequiredPasswordType": [
    "deviceDefault",
    "required",
    "numeric",
    "numericComplex",
    "alphabetic",
    "alphanumeric",
    "alphanumericWithSymbols",
    "lowSecurityBiometric",
    "customPassword"
  ],
  "androidForWorkRequiredPasswordType": [
    "deviceDefault",
    "lowSecurityBiometric",
    "required",
    "atLeastNumeric",
    "numericComplex",
    "atLeastAlphabetic",
    "atLeastAlphanumeric",
    "alphanumericWithSymbols"
  ],
  "androidRequiredPasswordComplexity": [
    "none",
    "low",
    "medium",
    "high"
  ],
  "androidRequiredPasswordType": [
    "deviceDefault",
    "alphabetic",
    "alphanumeric",
    "alphanumericWithSymbols",
    "lowSecurityBiometric",
    "numeric",
    "numericComplex",
    "any"
  ],
  "androidSafetyNetEvaluationType": [
    "basic",
    "hardwareBacked"
  ],
  "androidWorkProfileRequiredPasswordType": [
    "deviceDefault",
    "lowSecurityBiometric",
    "required",
    "atLeastNumeric",
    "numericComplex",
    "atLeastAlphabetic",
    "atLeastAlphanumeric",
    "alphanumericWithSymbols"
  ],
  "deviceComplianceActionType": [
    "noAction",
    "notification",
    "block",
    "retire",
    "wipe",
    "removeResourceAccessProfiles",
    "pushNotification",
    "remoteLock"
  ],
  "deviceThreatProtectionLevel": [
    "unavailable",
    "secured",
    "low",
    "medium",
    "high",
    "notSet"
  ],
  "macOSGatekeeperAppSources": [
    "notConfigured",
    "macAppStore",
    "macAppStoreAndIdentifiedDevelopers",
    "anywhere"
  ],
  "requiredPasswordType": [
    "deviceDefault",
    "alphanumeric",
    "numeric"
  ]
};

/** Fields of the objects some properties hold (one, or a list of them), and of one action for noncompliance. */
export const COMPLIANCE_OBJECTS: Record<string, Record<string, ComplianceFieldType>> = {
  "appListItem": {
    "appId": "string",
    "appStoreUrl": "string",
    "name": "string",
    "publisher": "string"
  },
  "deviceComplianceActionItem": {
    "actionType": {
      "enum": "deviceComplianceActionType"
    },
    "gracePeriodHours": "integer",
    "notificationTemplateId": "string"
  },
  "deviceCompliancePolicyScript": {
    "deviceComplianceScriptId": "string",
    "runIntervalInMinutes": "integer"
  },
  "operatingSystemVersionRange": {
    "description": "string",
    "highestVersion": "string",
    "lowestVersion": "string"
  },
  "wslDistributionConfiguration": {
    "distribution": "string",
    "maximumOSVersion": "string",
    "minimumOSVersion": "string"
  }
};
